resources:
  - 01-namespace.yaml
  - 02-imagestream.yaml
  - 03-buildconfig.yaml
  - 04-buildconfig-static-kas.yaml
  - 05-deploymentconfig.yaml
  - 06-service.yaml
  - 07-route.yaml
  - 08-serviceaccount.yaml
  - 09-rolebinding.yaml
  - 10-resourcequota.yaml
